### ISSUE TITLE
Do we want e.g. "share this" crap on pages for individual Stories? Blog posts?

### ISSUE THREAD

**Issue by DeckOfPandas** [DeckOfPandas/too-much-of-a-person#103]

**Comment by SunnyJimbles** [comment]
I don't think this is a must have. Do we have any analytics for how many people visited each page etc?

**Comment by DPatient** [comment]
Yes please! I think that would be great. And it pops up with the quote and the name of participant!

**Comment by DeckOfPandas** [comment]
Closing to rename and organise more tidily
