### ISSUE TITLE
Suggestion for grammar in blog post 2

### ISSUE THREAD

**Issue by DeckOfPandas** [DeckOfPandas/too-much-of-a-person#104]
@SunnyJimbles:
(keep meaning to say -- fricking *love* that name!)

I think that:

`...with 90% of British women have experienced street harassment for the first time during puberty...` 

might be better as

`...with 90% of British women [~~have~~] having experienced street harassment for the first time during puberty...`

Screenshot for context:
![screen shot 2018-07-05 at 04 03 00](https://user-images.githubusercontent.com/2399432/42300464-9686dcac-8008-11e8-94d8-db15e5e6e73f.png)

**Comment by SunnyJimbles** [comment]
Agreed, please change as you've suggested

**Comment by DeckOfPandas** [comment]
No worries

On re-reading, I actually think this...:

```
globally on average 84% of women are harassed on the street before they turn 17, with 90% of British women experiencing street harassment for the first time during puberty.
```

I'll brazenly put this in. Can update later as you like.

**Comment by DeckOfPandas** [comment]
Now live in #112
