### ISSUE TITLE
Hollabank Link Url to be changed

### ISSUE THREAD

**Issue by SunnyJimbles** [DeckOfPandas/too-much-of-a-person#108]
Could you please change the hyperlink for Hollaback! to this:
https://www.ihollaback.org/

The text is here: 
Unfortunately, the stats indicate that their experiences are far more common than mine. Studies conducted by **Hollaback!,**

**Comment by DeckOfPandas** [comment]
Sorry, unforgivable copy and paste error!

Fixed -- will close after pushing live (as discussed)

**Comment by DeckOfPandas** [comment]
Now live in #112
