### ISSUE TITLE
Title Change - query

### ISSUE THREAD

**Issue by SunnyJimbles** [DeckOfPandas/too-much-of-a-person#109]
@DPatient @DeckOfPandas 

Do you think the title should be "Get. Your. Tits. Out."
or "Get. Them. Tits. Out."

Or am I totally overthinking this?

**Comment by DeckOfPandas** [comment]
Overthinking is fine....it's kinda my thannnng anyway

I think you're right with "Them". You can change this after deployment if you insist (I'll can redirect the URL easily so any links that have been shared won't break or anything)

**Comment by SunnyJimbles** [comment]
Let's stick with them. No changes necessary.

**Comment by DeckOfPandas** [comment]
Closing :)
