### ISSUE TITLE
Audio look

### ISSUE THREAD

**Issue by DPatient** [DeckOfPandas/too-much-of-a-person#111]
I like the way the audio looks in the mock up I did. I don't like the patterns and busyness of the Soundcloud embed. 

I like the big black button here :  https://stownpodcast.org/chapter/1 and how much attention there is on the audio.

**Comment by DeckOfPandas** [comment]
See current draft in PR #168

**Comment by DeckOfPandas** [comment]
Closing to add new Issue covering all Story objects
