### ISSUE TITLE
When you link site my face is the thumbnail! Can we change to logo?

### ISSUE THREAD

**Issue by DPatient** [DeckOfPandas/too-much-of-a-person#116]
<img width="192" alt="screen shot 2018-07-12 at 17 35 52" src="https://user-images.githubusercontent.com/40503731/42646876-14ad2108-85fa-11e8-81d4-d42a916a78a6.png">
![toomuchofa person](https://user-images.githubusercontent.com/40503731/42646907-2753be3e-85fa-11e8-8289-3e586e0a8503.jpg)

**Comment by DeckOfPandas** [comment]
Fixed in #120
