### ISSUE TITLE
New cover styling

### ISSUE THREAD

**Issue by DPatient** [DeckOfPandas/too-much-of-a-person#176]
I'm not a fan of new logo and styling. Changes:

- Keep structured red box saying taking up all the space from before
- try black lines around the logo to box it

And if the above fails:
- Make the logo white text on black and keep the rest the same as the previous.

<img width="1339" alt="screen shot 2018-09-15 at 18 07 50" src="https://user-images.githubusercontent.com/40503731/45588795-8f540c00-b912-11e8-97b2-77a48bb5bdff.png">

**Comment by DeckOfPandas** [comment]
Can you give me details of the logo here, in case I need to redraw it in white on black as you say?

* Font
* Style (italic?)
* Font weight (bold? semi-bold? etc)
* Letter spacing

Unsolicited comment: do you definitely love the . on the end...?

**Comment by DeckOfPandas** [comment]
Please see PR #189 for current draft.

I tried the black lines, but it looked so funny that I can't even send you a screenshot... I might have misunderstood though. Basically, if you want black lines any closer to the words on the logo than the edge of the actual image, then it will be far easier to ask the designed to draw them than for me to add them.

P.S. I'm using the file with "twitter header" in its name, which looks to me to be 1500px by 500px at 72dpi. This is fine to my knowledge -- what do you think? A pedantic thing is that .png format was basically invented for use on the www, so we should probably default to using those (flat, not alphas ofc) unless there's some other reason not to.

**Comment by DeckOfPandas** [comment]
https://5bc4c810b13fb11db2834dd4--toomuchofaperson.netlify.com/ ???

**Comment by DeckOfPandas** [comment]
Current draft is now in PR #199

**Comment by DPatient** [comment]
Yeah I like this! I think the font is almost exactly what we want. Do you have more examples of graffiti handwriting?

**Comment by DeckOfPandas** [comment]
See new staging build in #202 for this plus new home logo and more

**Comment by DeckOfPandas** [comment]
Looks like this:
![screen shot 2018-12-19 at 11 52 58](https://user-images.githubusercontent.com/2399432/50218744-e25fb400-0384-11e9-912f-fdccb96e0e33.png)

**Comment by DeckOfPandas** [comment]
Done yonks ago in #202

**Comment by DeckOfPandas** [comment]
But, just for ref, the least-worst graffiti font I found was:
Sister Spray
https://www.dafont.com/sister-spray.font?text=TAKING+UP+ALL+THE+SPACE&psize=l&back=theme
