### ISSUE TITLE
Change home symbol to a hearth (the symbol of women's storytelling)

### ISSUE THREAD

**Issue by DPatient** [DeckOfPandas/too-much-of-a-person#177]
![image](https://user-images.githubusercontent.com/40503731/45588799-af83cb00-b912-11e8-9bc5-2309beea8fe2.png)
![image](https://user-images.githubusercontent.com/40503731/45588804-cd513000-b912-11e8-863f-d78a008bb2fd.png)

**Comment by DPatient** [comment]
![image](https://user-images.githubusercontent.com/40503731/45588814-012c5580-b913-11e8-9292-d8c1ebe74718.png)

**Comment by DeckOfPandas** [comment]
AMAZING

**Comment by DeckOfPandas** [comment]
See new staging build in #202 for this plus new cover

**Comment by DeckOfPandas** [comment]
Done yonks ago in #202
