### ISSUE TITLE
Story page layout

### ISSUE THREAD

**Issue by DeckOfPandas** [DeckOfPandas/too-much-of-a-person#182]
1. Audio objects (from #110, #111, whatsapp etc)

Awaiting guidance from @DPatient

**Comment by DeckOfPandas** [comment]
2. Would you like a "date published" thing on a Story?

**Comment by DeckOfPandas** [comment]
@DPatient 
Any instant feedback on this draft of the "related" section?

The aspect ratio is determined by the matrix photo you give me, as this is pretty much the only way to ensure you get the exact part of the image that you want. For ref, the ratio for this part on the-talks is 1.71.

![screen shot 2018-09-18 at 20 01 22](https://user-images.githubusercontent.com/2399432/45710137-ba8e6380-bb7d-11e8-9f70-03c0420f1572.png)

**Comment by DPatient** [comment]
Really like it!

**Comment by DPatient** [comment]
Good point! I think no.

**Comment by DeckOfPandas** [comment]
Photo gallery option:
http://photoswipe.com/

**Comment by DeckOfPandas** [comment]
Closing this to split out to new Issues on individual components of the page
