### ISSUE TITLE
Story project map

### ISSUE THREAD

**Issue by DeckOfPandas** [DeckOfPandas/too-much-of-a-person#183]
@DPatient @SunnyJimbles

Are you intending to publish all your Stories at launch, or just some then with others to be published on an ongoing basis?

**Comment by DPatient** [comment]
All 100 stories at launch xx

**Comment by DeckOfPandas** [comment]
# Summary

Amaaaaaaaaazing!!!! Just tell me what you need (other than, er, you know, the actual platform....) in order to help this happen!

Taggin @SunnyJimbles here now too @DPatient 

## ROADMAP

What is the planned launch date? We need to sit down to make the tech plan, as the last I heard of it the content was being vaguely added and I was to finish off the actual platform with a view to launch in late sept/early oct. No finger pointing, just want to know your plan to check it works from my end, plus from your tech POV with all content uploading etc.

## MY POSITION AND CAPACITY FOR THIS (tl;dr: big) (ohh, lol, yep, for both :p)

Basically, I will work on this project in all the time available this week where I am not too ill or at some formal medical thing or whatever, i.e. likely to be at least full time if not office hours. (If not blocked on feedback/signoff from you guys etc.) You guys are the only thing in my schedule and the only thing on my list... <3

## STORY DATA INPUT INTO THIS WEBSITE, UPLOADING TO YOUTUBE/SOUNDCLOUD etc

If adding data isn't working for you and your team for any reason, tell me Right Now. Don't hold back. I can try other things.

And ultimately, if in order to meet your launch you're going to need me to just input all your content myself from a list you provide, then I will......either by a day of tea and biscuits and drum n bass and swearing at my fingers and the fact that apostrophes are A Thing, or some other more sensible automagical way if you give me a spreadsheet with zero gaps and zero inconsistencies etc.

Basically, tell me what any problems are, because the worst that can happen is that I say "Sorry, I can't/won't help there", which...well, you know I would say that rather than equivocating. Trust is a good thing, and I hope I have yours.
