### ISSUE TITLE
New Team Member Prerna

### ISSUE THREAD

**Issue by DPatient** [DeckOfPandas/too-much-of-a-person#187]
Name: Prerna Winter
Role: Video Content Editor
![image](https://user-images.githubusercontent.com/40503731/45903825-e65e5300-bde2-11e8-8ecc-2f7972a494f4.png)

**Comment by DeckOfPandas** [comment]
@DPatient I would love to show you, or indeed anyone, how to do this.

The file to edit is '~/data/team.yaml', and images go in '_assets/images/team'. If you add the person's name and details in the file, then upload the image to that folder, you will automagically see a new card for them :)

team.yaml looks like this:
(familiar, right?)

```
#- title: "team"

- name: "Diana Patient"
  role: "Founder & Creative Director"
  photo: "diana_patient.JPG"
  email: diana@toomuchofaperson.com
          
- name: "Sunaina Dasgupta"
  role: "Strategy & Operations Director"
  photo: "sunaina_dasgupta.jpg"
  email: sunaina@toomuchofaperson.com

- name: "Amanda Robinson"
  role: "Story Seeker"
  photo: "amanda_dawn.JPG"
  email: amanda@toomuchofaperson.com

- name: "Emma Lock"
  role: "Story Seeker"
  photo: "emma_lock.jpg"
  email: emma@toomuchofaperson.com

- name: "Junia Bashiru"
  role: "Social Media Video Editor"
  photo: "junia_bashiru.jpg"
  email: junia@toomuchofaperson.com

- name: "Emma Donaldson"
  role: "Social Media Manager"
  photo: "emma_donaldson.jpg"
  email: diana@toomuchofaperson.com

- name: "Kyle Pickford"
  role: "Sound"
  photo: "kyle_pickford.jpg"
  email: diana@toomuchofaperson.com

- name: "Helen Jackson"
  role: "Web Developer"
  photo: "helen_jackson.jpg"
  email: helen@deckofpandas.com  
```

**Comment by DeckOfPandas** [comment]
Obviously just tell me to fuck off if any or all of you're too busy/this seems insane/this is incredibly patronising etc etc etc

**Comment by DeckOfPandas** [comment]
@DPatient 
From our recent chats I predict that now is not the time for you to look at this, so I will do it

...with huge apologies to Prerna for the delay :/

**Comment by DeckOfPandas** [comment]
Done in #200
