### ISSUE TITLE
Cant view 'Person' Text on Windows, Chrome

### ISSUE THREAD

**Issue by SunnyJimbles** [DeckOfPandas/too-much-of-a-person#30]
Here's the image. 
blob:https://web.whatsapp.com/dfd105c3-2a2f-4e0d-9b8d-6cca5b247653

**Comment by DeckOfPandas** [comment]
Sorry @SunnyJimbles , can you attach the image to this issue? You can either:
* drag and drop the file on to the text box
* click the "select" link below this window and choose the file to upload

**Comment by DeckOfPandas** [comment]
P.S. I'm sorry that this is annoying to get started with. Do bear with me -- I am so sure it's worth it...

**Comment by DeckOfPandas** [comment]
I'm going to close this since we changed the hero anyway. Please re-add if you still have the problem.
