### ISSUE TITLE
Boon now Link- appears twice 

### ISSUE THREAD

**Issue by SunnyJimbles** [DeckOfPandas/too-much-of-a-person#39]
The book now link and spiel appear twice - once after the about section and once at the bottom. Could we just leave the one at the bottom and remove the one that appears after the about section? Thanks.

**Comment by DeckOfPandas** [comment]
I think @DPatient likes this....?

**Comment by SunnyJimbles** [comment]
Hey, the purpose of the site is for people to view the project and for sponsors. I don't think we need two links to book on - can we just remove the top one? Thanks.

**Comment by DeckOfPandas** [comment]
Fixed, but going to mark this for a retrospective for my own education

**Comment by DeckOfPandas** [comment]
Done in #56
