### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by DeckOfPandas** [DeckOfPandas/too-much-of-a-person#390]
Missing all:
* Amina A
* Erinn D
* Esmeralda V
* Franco V
* Gemma R
* Harri R
* Holly S
* Irina T
* Janine B
* Jemma F
* Jenny G
* Jenny L
* Jessica H
* Joanna L
* Priscilla

Missing all other than matrix.jpg
* Teodora

Missing matrix.jpg
* Anne V
* Beatriz C
* Becka H
* Danielle J
* Maria Grazia

**Comment by DPatient** [comment]
? And then Anne V said that there everything was missing. Had the Anne V images just not been deployed?:
<img width="758" alt="Screenshot 2019-04-18 at 17 11 10" src="https://user-images.githubusercontent.com/40503731/56375279-fe714600-61fc-11e9-932f-99b6be9f3230.png">

**Comment by DPatient** [comment]
Could you create a folder for amina-a?
