### ISSUE TITLE
Franco wrong photos

### ISSUE THREAD

**Issue by DPatient** [DeckOfPandas/too-much-of-a-person#418]
<img width="783" alt="Screenshot 2019-04-18 at 21 42 18" src="https://user-images.githubusercontent.com/40503731/56390029-e4e2f500-6222-11e9-8568-7f385f73ea2e.png">
These are Charlotte's photos

**Comment by DeckOfPandas** [comment]
These are the photos in the Pull Request: https://github.com/DeckOfPandas/too-much-of-a-person/pull/400/files (Click on the 'Files Changed' tab on the right)

If you upload the correct ones I'll get them asap

**Comment by DPatient** [comment]
Uploading Franko's files now

**Comment by DeckOfPandas** [comment]
Done in #454
