### ISSUE TITLE
mette images broken

### ISSUE THREAD

**Issue by DPatient** [DeckOfPandas/too-much-of-a-person#419]
No images showing for Mette on her page

**Comment by DeckOfPandas** [comment]
The Pull Request for Mette on had one image: https://github.com/DeckOfPandas/too-much-of-a-person/pull/353/files

Just add the others and I'll grab them!

**Comment by DPatient** [comment]
OK will do now x

**Comment by DPatient** [comment]
Done!

**Comment by DeckOfPandas** [comment]
Done in #453
