### ISSUE TITLE
Do we need a heading for the audio so people know that what the sound is?

### ISSUE THREAD

**Issue by DPatient** [DeckOfPandas/too-much-of-a-person#420]

**Comment by DeckOfPandas** [comment]
Sure, let me know what you'd like to try and I'll mock it up

**Comment by DPatient** [comment]
<participant's name> Audio interview

Or just Audio interview

**Comment by DeckOfPandas** [comment]
Further ideas:
* In their own words
* Hear from them

**Comment by DeckOfPandas** [comment]
Done in #489
