### ISSUE TITLE
Ailie too many photos and one image repeated twice

### ISSUE THREAD

**Issue by DPatient** [DeckOfPandas/too-much-of-a-person#428]

**Comment by DPatient** [comment]
Take out the duplicate image please
<img width="1028" alt="Screenshot 2019-04-19 at 09 24 18" src="https://user-images.githubusercontent.com/40503731/56415355-68353280-6285-11e9-9304-085e06016e5e.png">

**Comment by DPatient** [comment]
Leave the main and on thumbnails take out 1st colour, 2nd full body black and white hair and of course the duplicate xx

**Comment by DeckOfPandas** [comment]
Deleted 2945, 3007, 3063, PR upcoming

**Comment by DeckOfPandas** [comment]
Done in #460
