### ISSUE TITLE
I need to re-upload Amanda's photos as I have edited them since to look better

### ISSUE THREAD

**Issue by DPatient** [DeckOfPandas/too-much-of-a-person#430]

**Comment by DPatient** [comment]
Uploaded under NEW amanda to same file

**Comment by DeckOfPandas** [comment]
I'm sorry D, I can't find these. Here is the current directory and contents: https://github.com/DeckOfPandas/too-much-of-a-person/tree/source/_assets/images/stories/amanda-r
