### ISSUE TITLE
reupload Becka

### ISSUE THREAD

**Issue by DPatient** [DeckOfPandas/too-much-of-a-person#432]

**Comment by DPatient** [comment]
deleted 1563 1560

**Comment by DPatient** [comment]
deleted 1554

**Comment by DPatient** [comment]
Proposed replacement photo files headed 'NEW replacement charlotte files'

**Comment by DeckOfPandas** [comment]
I got the files in #447 , but they are not of the same woman I can see in the current images marked "becka-h"

**Comment by DPatient** [comment]
Added x

**Comment by DeckOfPandas** [comment]
Done in #464
