### ISSUE TITLE
Scribbles bar is too tall

### ISSUE THREAD

**Issue by DPatient** [DeckOfPandas/too-much-of-a-person#44]
Scribbles bar is bigger than other bars. I would like it all the same please
<img width="1181" alt="screen shot 2018-06-22 at 22 00 20" src="https://user-images.githubusercontent.com/40503731/41799013-b6a81c08-7667-11e8-839e-88c42f06bd8a.png">

**Comment by DeckOfPandas** [comment]
Note to self: this is because the way the overlay inherits its size (:cover) makes it about 30px different in height to sections without a background image
