### ISSUE TITLE
Cutting off email address

### ISSUE THREAD

**Issue by DPatient** [DeckOfPandas/too-much-of-a-person#45]
and the email address should be Sun's here s
<img width="1101" alt="screen shot 2018-06-22 at 22 01 54" src="https://user-images.githubusercontent.com/40503731/41799101-06ac9f62-7668-11e8-8c79-2a44ef799d36.png">
unaina@toomuchofaperson.com

**Comment by DeckOfPandas** [comment]
Same reason as #49

**Comment by DeckOfPandas** [comment]
Fixed in #57
