### ISSUE TITLE
One-off fixes in Story spreadsheet parsing script

### ISSUE THREAD

**Issue by DeckOfPandas** [DeckOfPandas/too-much-of-a-person#462]
* Special character in Rebecca N
* John Dior full name

**Comment by DPatient** [comment]
Couldn't see the N and have added Dior to John

**Comment by DeckOfPandas** [comment]
As discussed, don’t use “John Dior” as their first name, just leave it how it is and I will pick it up from my end :)

**Comment by DeckOfPandas** [comment]
Done in #489
