### ISSUE TITLE
Photos: Becka has too many

### ISSUE THREAD

**Issue by DeckOfPandas** [DeckOfPandas/too-much-of-a-person#466]

**Comment by DeckOfPandas** [comment]
https://5cc0bbadbc14e60009883af9--toomuchofaperson.netlify.com/stories/becka-h/

**Comment by DPatient** [comment]
Hello! So here there is a mix of photos old and new. Can I send thm to you via wetransfer or something? Or shall I delete and reupload?

**Comment by DeckOfPandas** [comment]
Would you like me to just delete the older set, as per whatsapp conversation last night?

**Comment by DPatient** [comment]
Yes please!

**Comment by DeckOfPandas** [comment]
Done in #489
