### ISSUE TITLE
Participate heading for uniformity

### ISSUE THREAD

**Issue by DPatient** [DeckOfPandas/too-much-of-a-person#47]
<img width="963" alt="screen shot 2018-06-22 at 22 08 12" src="https://user-images.githubusercontent.com/40503731/41799288-ce788f2e-7668-11e8-9891-155a3fe3e50b.png">

**Comment by DeckOfPandas** [comment]
I think I understand what you mean. The point of this box is that it is indeed incongruous -- attention will go to it. I could e.g. make "want to take part...." larger? Bold? etc?

**Comment by DPatient** [comment]
I see so you wanted it to be different because it's a call to action? Happy to go with your judgement. It did look strange without a header as though it was an extension of the last box/section.

**Comment by DPatient** [comment]
Maybe bold will help that

**Comment by DeckOfPandas** [comment]
Fixed in #56
