### ISSUE TITLE
Quotation: Nancy’s short and long quotations are the same, plus typo

### ISSUE THREAD

**Issue by DeckOfPandas** [DeckOfPandas/too-much-of-a-person#477]
https://5cc0bbadbc14e60009883af9--toomuchofaperson.netlify.com/stories/nancy-d/

Missing open single quote at the start

**Comment by DPatient** [comment]
Same issue as Rahki

**Comment by DeckOfPandas** [comment]
Onit

**Comment by DeckOfPandas** [comment]
Superseded by #509 , closing
