### ISSUE TITLE
WHen clicking on Events it jumps too far

### ISSUE THREAD

**Issue by DPatient** [DeckOfPandas/too-much-of-a-person#49]
<img width="1440" alt="screen shot 2018-06-22 at 22 14 44" src="https://user-images.githubusercontent.com/40503731/41799522-bcdc08d0-7669-11e8-9252-80449eeef24d.png">

**Comment by DPatient** [comment]
Same for most of the buttons actually!

**Comment by DeckOfPandas** [comment]
Note to self: this is probably because of the <a> anchor links being in the wrong place for some sections

**Comment by DeckOfPandas** [comment]
Fixed in #57
