### ISSUE TITLE
Extra ' in Rakhi's short quotation

### ISSUE THREAD

**Issue by DeckOfPandas** [DeckOfPandas/too-much-of-a-person#508]
"Too much love' and getting too little. It’s the

**Comment by DPatient** [comment]
I put a space in to see if that meant the ' showed but appears to have doubled it?! Strange

**Comment by DeckOfPandas** [comment]
Leave this with me too!

**Comment by DeckOfPandas** [comment]
This is now duplicated by #479, but I think the fix will work!

Closing :)
