### ISSUE TITLE
Update to new MailChimp

### ISSUE THREAD

**Issue by DeckOfPandas** [DeckOfPandas/too-much-of-a-person#520]
Credentials elsewhere

**Comment by DPatient** [comment]
URL: http://eepurl.com/gpYYpn

**Comment by DPatient** [comment]
Updated: https://mailchi.mp/863bdbab312a/toomuchofaperson

**Comment by DPatient** [comment]
I can't find the embed link

**Comment by DPatient** [comment]
Is this what you needed?
Hope it worked xx

**Comment by DeckOfPandas** [comment]
@DPatient The link you gave me goes to this:

![Screen Shot 2019-05-29 at 13 01 15](https://user-images.githubusercontent.com/2399432/58555649-e9cb9900-8211-11e9-9d08-683f5470b058.png)

Previously I was asking for email address in a text box on our home page, whereas now the new window asks for the email address, so it's an extra step. Somewhere in your MailChimp account will be some code I can put on our own page, so we can remove the extra step. I can change the styling to be whatever you want of course too. I hope that makes sense!

**Comment by DPatient** [comment]
I’m confused… I think you probably need a sort of stripped down version of this but I’m not sure where I find the thing...

**Comment by DeckOfPandas** [comment]
I'll take this over as per WhatsApp chat just now!

**Comment by DeckOfPandas** [comment]
As per WhatsApp, I'm afraid there is now a new form... But I have tied it as a popup window to our existing red button.

**Comment by DeckOfPandas** [comment]
The next PR will close this. We can re-open if we want to re-address.
