### ISSUE TITLE
Facebook link not working 

### ISSUE THREAD

**Issue by SunnyJimbles** [DeckOfPandas/too-much-of-a-person#67]
When I click on the Facebook Icon at the bottom it doesn't work and takes me to an error page.

![image](https://user-images.githubusercontent.com/40495523/42026865-1ed85548-7ac0-11e8-8e80-7e6a24b9ae1c.png)

**Comment by DeckOfPandas** [comment]
Done, awaiting build

**Comment by DeckOfPandas** [comment]
Fixed
