### ISSUE TITLE
Contact - Social media / email buttons appear twice on webpage

### ISSUE THREAD

**Issue by SunnyJimbles** [DeckOfPandas/too-much-of-a-person#69]
The contact buttons appear twice, could you please remove this one? Thanks.

![image](https://user-images.githubusercontent.com/40495523/42027197-094e632e-7ac1-11e8-9dd8-05033a2c5575.png)

**Comment by DeckOfPandas** [comment]
Having social media links at the bottom of a web page is something that users come to expect. If you would prefer a different layout we can do that.

**Comment by DeckOfPandas** [comment]
It's fine, I'll get rid of them!

**Comment by SunnyJimbles** [comment]
No leave the bottom one, I wrote that half asleep. I meant the one above!

**Comment by SunnyJimbles** [comment]
Sorry, I should have been clearer.

**Comment by DeckOfPandas** [comment]
Fixed in #82
