### ISSUE TITLE
A lot of white space before and after the poem on Mobile 

### ISSUE THREAD

**Issue by SunnyJimbles** [DeckOfPandas/too-much-of-a-person#70]
There's too much white space - could we get rid of this or increase the font size of the poem? Thanks

![whatsapp image 2018-06-28 at 10 51 54](https://user-images.githubusercontent.com/40495523/42027379-779b97b6-7ac1-11e8-8425-456e1fa52db7.jpeg)

**Comment by DeckOfPandas** [comment]
Closing this. Please re-add if either of you aren't happy with how this looks atm.
