### ISSUE TITLE
Blog link doesn't work 

### ISSUE THREAD

**Issue by SunnyJimbles** [DeckOfPandas/too-much-of-a-person#77]
When I click on the link to read the blog, I get this error message: 
![image](https://user-images.githubusercontent.com/40495523/42037617-c4dbb35c-7ae0-11e8-98ba-33e946499cd4.png)

**Comment by DeckOfPandas** [comment]
It's there for me -- might just have taken a little longer to update for
you???

**Comment by SunnyJimbles** [comment]
Works now!
