### ISSUE TITLE
Text missing from blog post

### ISSUE THREAD

**Issue by SunnyJimbles** [DeckOfPandas/too-much-of-a-person#78]
Hey, I think you might have used an older version of the blog post - to be fair we only recently updated to include this line. Could you please amend/add it? Tank you. 

On a brisk March morning in London, the ‘Too Much of a Person’ contingent set out to join #March4Women **2018 which was calling for an end to gender-based discrimination and violence in workplaces all around the world​.**

**Comment by DeckOfPandas** [comment]
Done, build coming soon.

P.S. Thanks for adding the text change in here -- really really thoughtful, and saves me lots of time!

**Comment by DeckOfPandas** [comment]
Fixed in #82
