### ISSUE TITLE
Mailing list form should be loaded over SSL

### ISSUE THREAD

**Issue by DeckOfPandas** [DeckOfPandas/too-much-of-a-person#85]
Some browsers will start blocking this soon. We can wrap if necessary, but MailChimp must have a setting.

http://eepurl.com/dzq3ND

**Comment by DeckOfPandas** [comment]
@DPatient Was it you who set up your mailing list? When a user click the signup button on the website, we request the link to the list provider's signup service. We request SSL, but the form is only returned non-securely, which will probably actually be blocked in some browsers (and eventually by all). Is there some setting in the mailing list admin?

**Comment by DPatient** [comment]
It was me! I will look into that...

**Comment by DPatient** [comment]
Created a new account on mailchimp

**Comment by DeckOfPandas** [comment]
Closing as will be rolled in to #520
