### ISSUE TITLE
Add Becka and Priscilla content

### ISSUE THREAD

**Issue by DeckOfPandas** [DeckOfPandas/too-much-of-a-person#91]
![screen shot 2018-07-03 at 15 52 15](https://user-images.githubusercontent.com/2399432/42227307-20fa111e-7ed9-11e8-98c3-347ae265d197.png)

**Comment by DPatient** [comment]
Haven't completed Becka so just Priscilla! Do you need more than one?

**Comment by DeckOfPandas** [comment]
Closing for now as somewhat redundant (....I'm just listing priscilla ~20 times atm :p)
