### ISSUE TITLE
Post Blog on Thursday (5th July) at 11:30 am

### ISSUE THREAD

**Issue by SunnyJimbles** [DeckOfPandas/too-much-of-a-person#92]
Could you please post the blog which is in the folder "website TMOAP>blogs>blog post 2"  on google drive. All images in folder "Blogs>Blog post 2>Images"

**Comment by DeckOfPandas** [comment]
Pushed to staging site in #99 -- will close this when deployed to live

**Comment by DeckOfPandas** [comment]
Now live in #112
