### ISSUE TITLE
Find out if anyone is burning for blog posts to have tags

### ISSUE THREAD

**Issue by DeckOfPandas** [DeckOfPandas/too-much-of-a-person#96]

**Comment by SunnyJimbles** [comment]
Tags would be a nice to have, but would probably want it to provide all content for those tags- blogs, stories etc. Not a blocker for releasing second blog post.

**Comment by DPatient** [comment]
I think we have quite a narrow theme anyway but would be nice to filter by writer maybe?

**Comment by DeckOfPandas** [comment]
I would agree that this shouldn't block anything. I quite like the idea of filtering by writer perhaps. I'll park this for now, but we'll leave it open.

**Comment by DeckOfPandas** [comment]
Closing until we have more content and need more organisation
