### ISSUE TITLE
Add next/previous etc links to blog posts???

### ISSUE THREAD

**Issue by DeckOfPandas** [DeckOfPandas/too-much-of-a-person#97]

**Comment by SunnyJimbles** [comment]
This would be great - yes please.

**Comment by DeckOfPandas** [comment]
Feedback at your convenience please @SunnyJimbles @DPatient 

![screen shot 2018-07-05 at 17 51 54](https://user-images.githubusercontent.com/2399432/42336633-271f7a76-807c-11e8-952a-b16eb2402abc.png)

![screen shot 2018-07-05 at 17 52 41](https://user-images.githubusercontent.com/2399432/42336674-40ab8e94-807c-11e8-92ab-7666f3537be4.png)

**Comment by DeckOfPandas** [comment]
In #113  -- staging build can be seen at https://deckofpandas.github.io/too-much-of-a-person/ in about 5 mins from now
